version: '3'

services:
  nginx:
    build: nginx
    ports:
      # gogs ports
      - "80:80"
      - "443:443"
      # drone ports
      - "8443:8443"
      # docker registry ports
      - "5443:5443"

    restart: always
    links:
      - gogs:gogs
      - drone-server:drone-server
      - registry:registry

  gogs:
    image: gogs/gogs
    restart: always
    ports:
      - "3022:22"
    volumes:
      - ./var/gogs:/data

  drone-server:
    image: drone/drone:0.5
    ports:
      - "8000"
    volumes:
      - ./var/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_SECRET=xFbYh6rV
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=http://127.0.0.1
      - DRONE_GOGS_SKIP_VERIFY=true
    links:
      - registry:registry

  drone-agent:
    image: drone/drone:0.5
    command: agent
    restart: always
    depends_on: [ drone-server ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=xFbYh6rV

  registry:
    image: registry:2
    restart: always
    ports:
      - "5000"
    volumes:
      - /var/registry:/var/lib/registry
